In [1]:
import pandas as pd
import os
file_path_1 = os.path.join("Resources","purchase_data.json")
file_path_2 = os.path.join("Resources","purchase_data.json")

In [135]:
prch_data_1_df = pd.read_json(path_or_buf=file_path_1)
prch_data_2_df = pd.read_json(path_or_buf=file_path_2)
merged_df = prch_data_1_df.append(prch_data_2_df)
merged_df.reset_index(inplace=True)
merged_df

,index,Age,Gender,Item ID,Item Name,Price,SN
0,0,38,Male,165,Bone Crushing Silver Skewer,3.37,Aelalis34
1,1,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",2.32,Eolo46
2,2,34,Male,174,Primitive Blade,2.46,Assastnya25
3,3,21,Male,92,Final Critic,1.36,Pheusrical25
4,4,23,Male,63,Stormfury Mace,1.27,Aela59
5,5,20,Male,10,Sleepwalker,1.73,Tanimnya91
6,6,20,Male,153,Mercenary Sabre,4.57,Undjaskla97
7,7,29,Female,169,"Interrogator, Blood Blade of the Queen",3.32,Iathenudil29
8,8,25,Male,118,"Ghost Reaver, Longsword of Magic",2.77,Sondenasta63
9,9,31,Male,99,"Expiration, Warscythe Of Lost Worlds",4.53,Hilaerin92
10,10,24,Male,57,"Despair, Favor of Due Diligence",3.81,Chamosia29
11,11,20,Male,47,"Alpha, Reach of Ending Hope",1.55,Sally64
12,12,30,Male,81,Dreamkiss,4.06,Iskossa88
13,13,23,Male,77,"Piety, Guardian of Riddles",3.68,Seorithstilis90
14,14,40,Male,44,Bonecarvin Battle Axe,2.46,Sundast29
15,15,21,Male,96,Blood-Forged Skeletal Spine,4.77,Haellysu29
16,16,22,Female,123,Twilight's Carver,1.14,Sundista85
17,17,22,Female,59,"Lightning, Etcher of the King",1.65,Aenarap34
18,18,28,Male,91,Celeste,3.71,Iskista88
19,19,31,Male,177,"Winterthorn, Defender of Shifting Worlds",4.89,Assossa43
20,20,24,Male,78,"Glimmer, Ender of the Moon",2.33,Irith83
21,21,15,Male,3,Phantomlight,1.79,Iaralrgue74
22,22,11,Female,11,Brimstone,2.52,Deural48
23,23,19,Male,183,Dragon's Greatsword,2.36,Chanosia65
24,24,11,Male,65,Conqueror Adamantite Mace,1.96,Qarwen67
25,25,21,Male,63,Stormfury Mace,1.27,Idai61
26,26,29,Male,132,Persuasion,3.90,Aerithllora36
27,27,34,Male,106,Crying Steel Sickle,2.29,Assastnya25
28,28,15,Male,49,"The Oculus, Token of Lost Worlds",4.23,Ilariarin45
29,29,16,Female,45,Glinting Glass Edge,2.46,Phaedai25
...,...,...,...,...,...,...,...
1530,750,23,Male,86,Stormfury Lantern,1.28,Eollym91
1531,751,26,Female,179,"Wolf, Promise of the Moonwalker",1.88,Lisjasksda68
1532,752,15,Female,116,Renewed Skeletal Katana,2.37,Yalostiphos68
1533,753,20,Male,4,Bloodlord's Fetish,2.28,Thryallym62
1534,754,31,Male,104,Gladiator's Glaive,1.36,Sondastan54
1535,755,22,Female,179,"Wolf, Promise of the Moonwalker",1.88,Ailaesuir66
1536,756,22,Male,6,Rusty Skull,1.20,Siasri67
1537,757,35,Male,11,Brimstone,2.52,Seosri62
1538,758,20,Male,122,Unending Tyranny,1.21,Ryastycal90
1539,759,19,Male,87,"Deluge, Edge of the West",2.20,Chanirrasta87
1540,760,29,Male,81,Dreamkiss,4.06,Aerithllora36
1541,761,28,Male,175,Woeful Adamantite Claymore,1.24,Raeduerin33
1542,762,36,Male,52,Hatred,4.39,Lisosiast26
1543,763,27,Other / Non-Disclosed,48,"Rage, Legacy of the Lone Victor",4.32,Eurisuru25
1544,764,25,Male,70,Hope's End,3.89,Assassasda84
1545,765,15,Male,13,Serenity,1.49,Aerithnucal56
1546,766,22,Female,84,Arcane Gem,2.23,Nitherian58
1547,767,20,Male,122,Unending Tyranny,1.21,Hailaphos89
1548,768,21,Male,158,"Darkheart, Butcher of the Champion",3.56,Chamucosda93
1549,769,24,Male,73,Ritual Mace,3.74,Frichilsasya78
1550,770,22,Male,141,Persuasion,3.27,Aenasu69
1551,771,24,Male,25,Hero Cane,1.03,Lassista97
1552,772,15,Male,31,Trickster,2.07,Sidap51
1553,773,21,Male,44,Bonecarvin Battle Axe,2.46,Chamadarsda63
1554,774,24,Male,123,Twilight's Carver,1.14,Lassassast73
1555,775,22,Male,98,"Deadline, Voice Of Subtlety",3.62,Eural50
1556,776,14,Male,104,Gladiator's Glaive,1.36,Lirtossa78
1557,777,20,Male,117,"Heartstriker, Legacy of the Light",4.15,Tillyrin30
1558,778,20,Male,75,Brutality Ivory Warmace,1.72,Quelaton80
1559,779,23,Female,107,"Splitter, Foe Of Subtlety",3.61,Alim85

In [22]:
total_players = merged_df["SN"].nunique()
total_players

573

In [38]:
#Purchasing Analysis (Total)
#Number of Unique Items
#Average Purchase Price
#Total Number of Purchases
#Total Revenue
no_of_unique_items = merged_df["Item ID"].nunique()
print(f"Total number of unique items {no_of_unique_items}")
avg_purchase_price = merged_df["Price"].mean()
print("Average purchase price " '${:,.2f}'.format(avg_purchase_price))
total_revenue = merged_df["Price"].sum()
print("Total Revenue " '${:,.2f}'.format(total_revenue))

Total number of unique items 183
Average purchase price $2.93
Total Revenue $4,572.66

In [119]:
#Gender Demographics

#Percentage and Count of Male Players
#Percentage and Count of Female Players
#Percentage and Count of Other / Non-Disclosed
total_count = pd.to_numeric(total_players)
male_count = pd.to_numeric(merged_df[merged_df["Gender"] == 'Male']["SN"].nunique())
male_percentage = male_count*100/total_count
female_count =  pd.to_numeric(merged_df[merged_df["Gender"] == 'Female']["SN"].nunique())
female_percentage = female_count*100/total_count
other_count = total_count - male_count - female_count
other_percentage = other_count*100/total_count
print(f"Number of male counts is {male_count} and percentage wise it is {male_percentage}")
print(f"Number of female counts is {female_count} and percentage wise it is {female_percentage}")
print(f"Number of other counts is {other_count} and percentage wise it is {other_percentage}")

Number of male counts is 465 and percentage wise it is 81.15183246073299
Number of female counts is 100 and percentage wise it is 17.452006980802793
Number of other counts is 8 and percentage wise it is 1.3961605584642234

In [130]:
#Purchasing Analysis (Gender)

#The below each broken by gender
#Purchase Count
#Average Purchase Price
#Total Purchase Value
#Normalized Totals
total_purchase =  merged_df["Price"].sum()
male_df = merged_df[merged_df["Gender"] == 'Male']
male_purchase_count = male_df["Gender"].count()
male_avg_purchase =  male_df["Price"].mean()
male_total_purchase = male_df["Price"].sum()
male_normal_purchase = male_total_purchase/male_count
print("-------------------MALE PURCHASE-----------")
print(f"Total purchase counts by male players {male_purchase_count}")
print("Average purchase price for male players "'${:,.2f}'.format(male_avg_purchase))
print("Total purchase price by male players "'${:,.2f}'.format(male_total_purchase))
print("Number of dollars spent by a single male player is "'${:,.2f}'.format(male_normal_purchase))

print("-------------------FEMALE PURCHASE-----------")
female_df = merged_df[merged_df["Gender"] == 'Female']
female_purchase_count = female_df["Gender"].count()
female_avg_purchase =  female_df["Price"].mean()
female_total_purchase = female_df["Price"].sum()
female_normal_purchase = female_total_purchase/female_count
print(f"Total purchase counts byfe male players {female_purchase_count}")
print("Average purchase price for female players "'${:,.2f}'.format(female_avg_purchase))
print("Total purchase price by female players "'${:,.2f}'.format(female_total_purchase))
print("Number of dollars spent by a single female player is "'${:,.2f}'.format(female_normal_purchase))

print("-------------------OTHER PURCHASE-----------")
other_df = merged_df[(merged_df["Gender"] != 'Female')  & (merged_df["Gender"] != 'Male')]
other_purchase_count = other_df["Gender"].count()
other_avg_purchase =  other_df["Price"].mean()
other_total_purchase = other_df["Price"].sum()
other_normal_purchase = other_total_purchase/other_count
print(f"Total purchase counts by other players {other_purchase_count}")
print("Average purchase price for other players "'${:,.2f}'.format(other_avg_purchase))
print("Total purchase price by other players "'${:,.2f}'.format(other_total_purchase))
print("Number of dollars spent by a single other player is "'${:,.2f}'.format(other_normal_purchase))

-------------------MALE PURCHASE-----------
Total purchase counts by male players 1266
Average purchase price for male players $2.95
Total purchase price by male players $3,735.36
Number of dollars spent by a single male player is $8.03
-------------------FEMALE PURCHASE-----------
Total purchase counts byfe male players 272
Average purchase price for female players $2.82
Total purchase price by female players $765.82
Number of dollars spent by a single female player is $7.66
-------------------OTHER PURCHASE-----------
Total purchase counts by other players 22
Average purchase price for other players $3.25
Total purchase price by other players $71.48
Number of dollars spent by a single other player is $8.93

In [184]:
#Age Demographics

#The below each broken into bins of 4 years (i.e. <10, 10-14, 15-19, etc.)
##Purchase Count
#Average Purchase Price
#Total Purchase Value
#Normalized Totals
bins=[0,10,14,19,24,29,34,39,44,49,54]
# Create labels for these bins
group_labels = ["<10","10-14","15-19","20-24","25-29","30-34",
                "35-39","40-44","45-49",">=75"]

# Slice the data and place it into bins
pd.cut(pd.to_numeric(merged_df["Age"]),bins,labels=group_labels).head()

# Place the data series into a new column inside of the DataFrame
merged_df["Age Group"] = pd.cut(merged_df["Age"],bins,labels=group_labels)
grouped_by_age_groups = merged_df.groupby(['Age Group'])
group_by_age_summary = pd.DataFrame({"Purchase Count":grouped_by_age_groups["Age"].count(),
                                   "Average Purchase Price":grouped_by_age_groups["Price"].mean(),
                                "Total Purchase Value":grouped_by_age_groups["Price"].sum(),"Normalized Totals":grouped_by_age_groups["Price"].sum()/total_purchase})
group_by_age_summary.reset_index(inplace=True)
group_by_age_summary.dropna(how="any")

,Age Group,Average Purchase Price,Normalized Totals,Purchase Count,Total Purchase Value
0,10-14,2.702903,0.036648,62,167.58
1,15-19,2.905414,0.169013,266,772.84
2,20-24,2.913006,0.428097,672,1957.54
3,25-29,2.962640,0.161976,250,740.66
4,30-34,3.082031,0.086274,128,394.50
5,35-39,2.842857,0.052223,84,238.80
6,40-44,3.189375,0.022320,32,102.06
7,45-49,2.720000,0.001190,2,5.44
8,<10,3.019375,0.042260,64,193.24

In [212]:
group_by_username = merged_df.groupby(['SN'])

group_by_username["Price"].sum()
total_spender_summary = pd.DataFrame(group_by_username["Price"].sum())
renamed_spender_summary = total_spender_summary.rename(columns={"Price":"Total Purchase Value"})
# Sort by strongest Pokemon
highest_spender = renamed_spender_summary.sort_values(["Total Purchase Value"], ascending=False)

highest_spender["Purchase Count"] = pd.DataFrame(group_by_username["SN"].count())

highest_spender["Average Purchase Price"] = pd.DataFrame(group_by_username["Price"].mean())
highest_spender

               Total Purchase Value  Purchase Count  Average Purchase Price
SN
Undirrala66                   34.12              10                3.412000
Saedue76                      27.12               8                3.390000
Mindimnya67                   25.48               8                3.185000
Haellysu29                    25.46               6                4.243333
Eoda93                        23.16               6                3.860000
Isursti83                     22.10               6                3.683333
Isurria36                     22.02               6                3.670000
Eusri70                       21.10               6                3.516667
Aerithllora36                 20.90               6                3.483333
Yasriphos60                   20.80               6                3.466667
Sondastan54                   20.48               8                2.560000
Haerith37                     20.28               6                3.380000
Chadjask77                    20.02               6                3.336667
Qarwen67                      19.94               8                2.492500
Sondim43                      18.76               6                3.126667
Tillyrin30                    18.38               6                3.063333
Lisistaya47                   18.38               6                3.063333
Tyisriphos58                  18.36               4                4.590000
Frichaya88                    18.32               6                3.053333
Assassasta79                  18.24               4                4.560000
Lisossan98                    18.20               4                4.550000
Yadanun74                     18.18               6                3.030000
Mindirra92                    18.02               6                3.003333
Aeliru63                      17.96               4                4.490000
Chanastsda67                  17.92               6                2.986667
Frichosiala98                 17.88               6                2.980000
Malunil62                     17.78               4                4.445000
Iskadarya95                   17.58               4                4.395000
Ilogha82                      17.22               4                4.305000
Yadaisuir65                   17.12               4                4.280000
...                             ...             ...                     ...
Rithe53                        2.72               2                1.360000
Pheusrical25                   2.72               2                1.360000
Isketo41                       2.64               2                1.320000
Tyaili86                       2.56               2                1.280000
Eollym91                       2.56               2                1.280000
Chamirra53                     2.56               2                1.280000
Ilaststa70                     2.54               2                1.270000
Aela59                         2.54               2                1.270000
Lassilsa63                     2.54               2                1.270000
Mindosiasya28                  2.48               2                1.240000
Raeduerin33                    2.48               2                1.240000
Heolo60                        2.48               2                1.240000
Ialidru40                      2.48               2                1.240000
Yaristi64                      2.48               2                1.240000
Ilrian97                       2.48               2                1.240000
Ryastycal90                    2.42               2                1.210000
Ilast79                        2.40               2                1.200000
Siasri67                       2.40               2                1.200000
Undirrasta74                   2.32               2                1.160000
Sundista85                     2.28               2                1.140000
Chamirrasya33                  2.22               2                1.110000
Eyircil84                      2.12               2                1.060000
Sondassa68                     2.12               2                1.060000
Lassadarsda57                  2.06               2                1.030000
Tridaira71                     2.06               2                1.030000
Rarith48                       2.06               2                1.030000
Alaesu91                       2.06               2                1.030000
Mindossa76                     2.06               2                1.030000
Lassista97                     2.06               2                1.030000
Ililsan66                      2.06               2                1.030000

[573 rows x 3 columns]